export interface TopicCategory {
  id: string;
  displayLabel: string;
  icon: string;
  keywords: string[];
  contextTerms: string[];
}

export const TOPIC_CATEGORIES: TopicCategory[] = [
  {
    id: 'micro-interaction',
    displayLabel: 'Micro Interaction',
    icon: '✨',
    keywords: [
      'micro interaction',
      'microinteraction',
      'hover effect',
      'hover animation',
      'loading animation',
      'skeleton loader',
      'transition effect',
      'button animation',
      'scroll animation',
      'parallax',
      'lottie',
      'motion design',
    ],
    contextTerms: [
      'animation',
      'transition',
      'easing',
      'keyframe',
      'CSS animation',
      'framer motion',
      'GSAP',
      'spring',
      'gesture',
      'feedback',
      'delightful',
    ],
  },
  {
    id: 'ui-ux',
    displayLabel: 'UI/UX',
    icon: '🎨',
    keywords: [
      'UI design',
      'UX design',
      'user interface',
      'user experience',
      'design system',
      'figma',
      'usability',
      'wireframe',
      'prototype',
      'design token',
      'accessibility',
      'a11y',
    ],
    contextTerms: [
      'typography',
      'color palette',
      'spacing',
      'layout',
      'responsive',
      'mobile first',
      'dark mode',
      'component library',
      'style guide',
      'Sketch',
      'Adobe XD',
    ],
  },
  {
    id: 'component',
    displayLabel: 'Component',
    icon: '🧩',
    keywords: [
      'React component',
      'Vue component',
      'web component',
      'Svelte component',
      'Angular component',
      'shadcn',
      'radix ui',
      'headless ui',
      'component library',
      'storybook',
    ],
    contextTerms: [
      'reusable',
      'composable',
      'props',
      'slots',
      'render',
      'JSX',
      'template',
      'atomic design',
      'compound component',
      'polymorphic',
    ],
  },
  {
    id: 'widget',
    displayLabel: 'Widget',
    icon: '📦',
    keywords: [
      'dashboard widget',
      'embed widget',
      'chat widget',
      'calendar widget',
      'notification widget',
      'data widget',
      'widget toolkit',
      'embeddable',
    ],
    contextTerms: [
      'embed',
      'iframe',
      'plugin',
      'integration',
      'dashboard',
      'card',
      'tile',
      'sidebar',
      'toolbar',
      'panel',
    ],
  },
  {
    id: 'claude',
    displayLabel: 'Claude',
    icon: '🤖',
    keywords: [
      'Claude AI',
      'Claude 3',
      'Claude Opus',
      'Claude Sonnet',
      'Claude Haiku',
      'Anthropic',
      'Claude API',
      'claude.ai',
      'Claude Code',
      'Claude',
    ],
    contextTerms: [
      'LLM',
      'large language model',
      'AI assistant',
      'prompt',
      'token',
      'context window',
      'constitutional AI',
      'RLHF',
      'safety',
    ],
  },
  {
    id: 'claude-workflow',
    displayLabel: 'Claude Workflow',
    icon: '⚡',
    keywords: [
      'Claude workflow',
      'AI workflow',
      'prompt chain',
      'prompt engineering',
      'AI automation',
      'LLM pipeline',
      'AI agent',
      'tool use',
      'function calling',
      'MCP',
      'model context protocol',
    ],
    contextTerms: [
      'chain of thought',
      'few-shot',
      'system prompt',
      'retrieval',
      'RAG',
      'embedding',
      'vector',
      'orchestration',
      'agentic',
    ],
  },
  {
    id: 'design-role',
    displayLabel: 'Design Role',
    icon: '👤',
    keywords: [
      'design career',
      'design leadership',
      'design manager',
      'head of design',
      'VP design',
      'design director',
      'principal designer',
      'staff designer',
      'design IC',
      'design interview',
    ],
    contextTerms: [
      'career growth',
      'promotion',
      'portfolio',
      'design critique',
      'design review',
      'mentorship',
      'leadership',
      'IC track',
      'management track',
    ],
  },
  {
    id: 'hiring-designer',
    displayLabel: 'Hiring Designer',
    icon: '💼',
    keywords: [
      'hiring designer',
      'design job',
      'UX job',
      'UI job',
      'product designer job',
      'design hiring',
      'we are hiring',
      "we're hiring",
      'looking for a designer',
      'design opening',
      'design role open',
    ],
    contextTerms: [
      'remote',
      'hybrid',
      'full-time',
      'contract',
      'freelance',
      'salary',
      'compensation',
      'benefits',
      'startup',
      'apply',
      'portfolio',
    ],
  },
  {
    id: 'frontend-dev',
    displayLabel: 'Frontend Dev',
    icon: '💻',
    keywords: [
      'frontend',
      'front-end',
      'React',
      'Next.js',
      'Vue',
      'Svelte',
      'Angular',
      'Tailwind',
      'CSS-in-JS',
      'TypeScript',
      'JavaScript',
      'Vite',
      'webpack',
    ],
    contextTerms: [
      'bundle',
      'SSR',
      'SSG',
      'hydration',
      'virtual DOM',
      'state management',
      'hooks',
      'server components',
      'edge runtime',
      'performance',
    ],
  },
  {
    id: 'ai-ml',
    displayLabel: 'AI/ML',
    icon: '🧠',
    keywords: [
      'machine learning',
      'deep learning',
      'neural network',
      'GPT',
      'transformer',
      'diffusion model',
      'fine-tuning',
      'training data',
      'inference',
      'OpenAI',
      'Hugging Face',
    ],
    contextTerms: [
      'model',
      'dataset',
      'benchmark',
      'SOTA',
      'paper',
      'research',
      'compute',
      'GPU',
      'parameter',
      'weight',
      'attention',
      'loss function',
    ],
  },
];
